In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from statsmodels.discrete.discrete_model import Logit
from statsmodels.tools.tools import add_constant
import numpy as np

In [2]:
titanic = pd.read_csv('./train.csv', index_col=0)
titanic.head(3)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S

In [3]:
titanic['Sex'] = titanic['Sex'] == 'male'
titanic['Sex'] = titanic['Sex'].astype(int)
titanic['Sex']

PassengerId
1      1
2      0
3      0
4      0
5      1
      ..
887    1
888    0
889    0
890    1
891    1
Name: Sex, Length: 891, dtype: int64

In [4]:
import numpy as np

X = titanic[['Sex']]
y = titanic['Survived']


def sigmoid(val):
    return 1/(1+np.exp(-val))

# define a model equation

b = 1.06  # bias/ intercept
a = -2.51 # weight

p = sigmoid(b + X['Sex']*a)


# define a loss function

def log_loss(y, p):
    return - np.sum(y*np.log(p) + (1-y)*np.log(1-p))

log_loss(y, p)

458.9045563856602

In [8]:
logreg = LogisticRegression(penalty='none')
logreg.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='none',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
logreg.coef_

array([[-2.51371812]])

In [10]:
logreg.intercept_

array([1.05659211])

In [15]:
1/(1+np.exp(-1.057+2.5137))

0.18897257057213832

In [16]:
logreg.predict_proba(pd.DataFrame({'Sex':[0, 1]}))

array([[0.25796125, 0.74203875],
       [0.81109271, 0.18890729]])

In [17]:
logit = Logit(y, add_constant(X))
f = logit.fit()
f.summary()

Optimization terminated successfully.
         Current function value: 0.515041
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Survived   No. Observations:                  891
Model:                          Logit   Df Residuals:                      889
Method:                           MLE   Df Model:                            1
Date:                Wed, 27 May 2020   Pseudo R-squ.:                  0.2266
Time:                        12:27:11   Log-Likelihood:                -458.90
converged:                       True   LL-Null:                       -593.33
Covariance Type:            nonrobust   LLR p-value:                 2.020e-60
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.0566      0.129      8.191      0.000       0.804       1.309
Sex           -2.5137      0.167    -15.036      0.000      -2.841      -2.186
==============================================================================
"""

In [18]:
print(logreg.intercept_, logreg.coef_)

[1.05659211] [[-2.51371812]]
